export const prompts = [
	"What does it mean to live a good life?",
	"Reflect on the quote: 'The unexamined life is not worth living.' - Socrates",
	"Describe your ideal day. How does it reflect your values?",
	"What are you grateful for today, and why?",
	"How do you define success?",
	"Reflect on the quote: 'Happiness depends upon ourselves.' - Aristotle",
	"What is one thing you could do today to make someone else's life better?",
	"What is your earliest memory? How does it shape who you are today?",
	"What is your relationship with time?",
	"Reflect on the quote: 'Man is the measure of all things.' - Protagoras",
	"What role does fear play in your life?",
	"Describe a recent situation where you felt truly alive.",
	"What is something you've always wanted to learn, and why?",
	"Reflect on the quote: 'He who has a why to live can bear almost any how.' - Friedrich Nietzsche",
	"What does freedom mean to you?",
	"Write about a time when you had to make a difficult decision. What did you learn?",
	"What do you love most about yourself?",
	"Reflect on the quote: 'Hell is other people.' - Jean-Paul Sartre",
	"What is one thing you wish you could tell your younger self?",
	"How do you define truth?",
	"Reflect on the quote: 'The only thing I know is that I know nothing.' - Socrates",
	"Write about a person who has deeply influenced your life.",
	"What does kindness mean to you?",
	"Describe a place where you feel at peace.",
	"Reflect on the quote: 'Life must be understood backward. But it must be lived forward.' - Søren Kierkegaard",
	"What is the most challenging thing about being human?",
	"Write about a moment when you overcame self-doubt.",
	"What do you think is humanity's greatest achievement?",
	"Reflect on the quote: 'It is not length of life, but depth of life.' - Ralph Waldo Emerson",
	"What is your greatest hope for the future?",
	"Describe your relationship with nature.",
	"What does love mean to you?",
	"Reflect on the quote: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.' - Aristotle",
	"What is your biggest regret, and what have you learned from it?",
	"What would you do if money weren't a factor in your life?",
	"Reflect on the quote: 'Happiness is not something ready made. It comes from your own actions.' - Dalai Lama",
	"What does justice mean to you?",
	"Describe a dream you've had recently.",
	"What does it mean to be creative?",
	"Reflect on the quote: 'In the middle of difficulty lies opportunity.' - Albert Einstein",
	"Write about a time when you felt deeply connected to someone.",
	"What is your relationship with technology?",
	"What do you think is the purpose of art?",
	"Reflect on the quote: 'An eye for an eye only ends up making the whole world blind.' - Mahatma Gandhi",
	"What is your proudest achievement?",
	"How do you find meaning in everyday life?",
	"Write about a time when you felt completely lost.",
	"Reflect on the quote: 'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.' - Buddha",
	"What does forgiveness mean to you?",
	"Describe a person you admire and why.",
	"What does it mean to grow up?",
	"Reflect on the quote: 'Man is free at the moment he wishes to be.' - Voltaire",
	"What do you think happens after death?",
	"Write about your relationship with your body.",
	"What does resilience mean to you?",
	"Reflect on the quote: 'Life is what happens to us while we are making other plans.' - Allen Saunders",
	"What is your most vivid childhood memory?",
	"Write about a time you felt truly happy.",
	"What does it mean to be wise?",
	"Reflect on the quote: 'It does not matter how slowly you go as long as you do not stop.' - Confucius",
	"What is your relationship with change?",
	"Describe a time when you had to let go of something or someone.",
	"What is one thing you would change about the world, and why?",
	"Reflect on the quote: 'The only true wisdom is in knowing you know nothing.' - Socrates",
	"What does courage mean to you?",
	"Write about a moment of serendipity in your life.",
	"How do you handle failure?",
	"Reflect on the quote: 'Be yourself; everyone else is already taken.' - Oscar Wilde",
	"What does success look like to you?",
	"Write about a book, movie, or song that has deeply impacted you.",
	"What do you think is the most important quality in a friend?",
	"Reflect on the quote: 'No man ever steps in the same river twice.' - Heraclitus",
	"What is one thing you wish you understood better?",
	"Describe a moment when you felt completely at peace.",
	"What does integrity mean to you?",
	"Reflect on the quote: 'Knowing yourself is the beginning of all wisdom.' - Aristotle",
	"What is your relationship with risk?",
	"Write about a time when you were outside your comfort zone.",
	"What do you think is the key to happiness?",
	"Reflect on the quote: 'Not all those who wander are lost.' - J.R.R. Tolkien",
	"What does it mean to be free?",
	"Write about a time when you felt deeply moved by something.",
	"How do you balance your wants and needs?",
	"Reflect on the quote: 'A journey of a thousand miles begins with a single step.' - Lao Tzu",
	"What is your relationship with power?",
	"Describe a time when you stood up for what you believed in.",
	"What do you think is the most important lesson life has taught you?",
	"Reflect on the quote: 'Be the change that you wish to see in the world.' - Mahatma Gandhi",
	"What does it mean to be human?",
	"Write about a time when you felt completely understood.",
	"What does authenticity mean to you?",
	"Reflect on the quote: 'Do what you can, with what you have, where you are.' - Theodore Roosevelt",
	"What is your relationship with your dreams?",
	"Write about a time you surprised yourself.",
	"What do you think is the most beautiful thing in the world?",
	"Reflect on the quote: 'To live is the rarest thing in the world. Most people exist, that is all.' - Oscar Wilde",
	"What does empathy mean to you?",
	"Write about a time when you felt truly free.",
	"How do you define home?",
	"Reflect on the quote: 'The mind is everything. What you think you become.' - Buddha",
	"What is your relationship with ambition?",
	"Describe a time when you learned something new about yourself.",
	"What do you think is the most important thing in life?",
	"Reflect on the quote: 'Don't cry because it's over, smile because it happened.' - Dr. Seuss",
	"What does it mean to be generous?",
	"Write about a moment when you felt deeply connected to the universe.",
	"What do you think is the greatest mystery of life?",
	"Reflect on the quote: 'Happiness is not having what you want. It is wanting what you have.' - Rabbi Hyman Schachtel",
	"What is your relationship with failure?",
	"Write about a time when you forgave someone.",
	"What does it mean to have faith?",
	"Reflect on the quote: 'Do not go where the path may lead, go instead where there is no path and leave a trail.' - Ralph Waldo Emerson",
	"What is one thing you hope to accomplish in your lifetime?",
	"Describe a moment when you felt deeply inspired.",
	"What does patience mean to you?",
	"Reflect on the quote: 'Success is not final, failure is not fatal: It is the courage to continue that counts.' - Winston Churchill",
	"What is your relationship with self-discipline?",
	"Write about a time when you felt out of control.",
	"What do you think is the role of education in life?",
	"Reflect on the quote: 'Our lives begin to end the day we become silent about things that matter.' - Martin Luther King Jr.",
	"What does honesty mean to you?",
	"Describe a person who has shown you unconditional love.",
	"What do you think is the most important quality in a leader?",
	"Reflect on the quote: 'The greatest glory in living lies not in never falling, but in rising every time we fall.' - Nelson Mandela",
	"What is your relationship with hope?",
	"Write about a time when you felt completely at ease with yourself.",
	"What do you think is the most valuable resource in the world?",
	"Reflect on the quote: 'The best way to predict the future is to create it.' - Peter Drucker",
	"What does humility mean to you?",
	"Describe a time when you were surprised by someone's kindness.",
	"What do you think is the secret to a long-lasting relationship?",
	"Reflect on the quote: 'Peace begins with a smile.' - Mother Teresa",
	"What is your relationship with gratitude?",
	"Write about a time when you felt overwhelmed by beauty.",
	"What do you think is the most important thing you've learned from your mistakes?",
	"Reflect on the quote: 'The only limit to our realization of tomorrow will be our doubts of today.' - Franklin D. Roosevelt",
	"What does balance mean to you?",
	"Describe a moment when you felt completely out of your depth.",
	"What do you think is the most important quality in a teacher?",
	"Reflect on the quote: 'It is during our darkest moments that we must focus to see the light.' - Aristotle",
	"What is your relationship with self-care?",
	"Write about a time when you felt truly valued.",
	"What do you think is the role of curiosity in life?",
	"Reflect on the quote: 'The weak can never forgive. Forgiveness is the attribute of the strong.' - Mahatma Gandhi",
	"What does it mean to live authentically?",
	"Describe a time when you felt like you truly belonged.",
	"What do you think is the most important thing you've learned about love?",
	"Reflect on the quote: 'If you want to go fast, go alone. If you want to go far, go together.' - African Proverb",
	"What is your relationship with ambition?",
	"Write about a time when you had to confront your fears.",
	"What do you think is the most important quality in a partner?",
	"Reflect on the quote: 'Injustice anywhere is a threat to justice everywhere.' - Martin Luther King Jr.",
	"What does it mean to be compassionate?",
	"Describe a moment when you felt truly independent.",
	"What do you think is the role of imagination in life?",
	"Reflect on the quote: 'Imagination is more important than knowledge. For knowledge is limited, whereas imagination embraces the entire world.' - Albert Einstein",
	"What is your relationship with fear?",
	"Write about a time when you felt like you made a difference.",
	"What do you think is the most important quality in a parent?",
	"Reflect on the quote: 'A person who never made a mistake never tried anything new.' - Albert Einstein",
	"What does it mean to be brave?",
	"Describe a moment when you felt truly seen.",
	"What do you think is the most important thing you've learned about yourself?",
	"Reflect on the quote: 'You must be the master of your own destiny.' - Napoleon Hill",
	"What is your relationship with destiny?",
	"Write about a time when you had to adapt to change.",
	"What do you think is the most important thing you've learned from your family?",
	"Reflect on the quote: 'It is not what we get. But who we become, what we contribute... that gives meaning to our lives.' - Tony Robbins",
	"What does it mean to be vulnerable?",
	"Describe a time when you felt truly powerful.",
	"What do you think is the most important thing you've learned from your friends?",
	"Reflect on the quote: 'Your time is limited, so don't waste it living someone else's life.' - Steve Jobs",
	"What is your relationship with failure?",
	"Write about a time when you had to face your limits.",
	"What do you think is the most important thing you've learned from your challenges?",
	"Reflect on the quote: 'Life is 10% what happens to us and 90% how we react to it.' - Charles R. Swindoll",
	"What does it mean to be hopeful?",
	"Describe a moment when you felt truly at home.",
	"What do you think is the most important thing you've learned about trust?",
	"Reflect on the quote: 'Trust yourself. You know more than you think you do.' - Benjamin Spock",
	"What is your relationship with patience?",
	"Write about a time when you felt deeply moved by someone else's story.",
	"What do you think is the most important thing you've learned about forgiveness?",
	"Reflect on the quote: 'We are all in the gutter, but some of us are looking at the stars.' - Oscar Wilde",
	"What does it mean to live with purpose?",
	"Describe a moment when you felt truly in love.",
	"What do you think is the most important thing you've learned about resilience?",
	"Reflect on the quote: 'Resilience is knowing that you are the only one that has the power and the responsibility to pick yourself up.' - Mary Holloway",
	"What is your relationship with joy?",
	"Write about a time when you felt a sense of awe.",
	"What do you think is the most important thing you've learned about yourself this year?",
	"Reflect on the quote: 'Do not let what you cannot do interfere with what you can do.' - John Wooden",
	"What does it mean to live with intention?",
	"Describe a moment when you felt completely at peace with the world.",
	"What is your relationship with self-expression?",
	"Write about a time when you felt completely understood by someone else.",
	"What do you think is the most important thing you've learned about happiness?",
	"Reflect on the quote: 'Happiness is not something ready made. It comes from your own actions.' - Dalai Lama",
	"What does it mean to live with gratitude?",
	"Describe a moment when you felt truly free.",
	"What do you think is the most important thing you've learned about peace?",
	"Reflect on the quote: 'Peace cannot be kept by force; it can only be achieved by understanding.' - Albert Einstein",
	"What is your relationship with love?",
	"Write about a time when you felt truly connected to someone else.",
	"What do you think is the most important thing you've learned about connection?",
	"Reflect on the quote: 'Love is composed of a single soul inhabiting two bodies.' - Aristotle",
	"What does it mean to live authentically?",
	"Describe a moment when you felt completely yourself.",
	"What do you think is the most important thing you've learned about authenticity?",
	"Reflect on the quote: 'Be yourself; everyone else is already taken.' - Oscar Wilde",
	"What is your relationship with truth?",
	"Write about a time when you discovered something profound.",
	"Take a bad habit you have and list every negative effect it has on your life.",
	"What external things am I trying to control today? How can I shift my focus inward?",
	"What story am I telling myself about a current struggle?",
	"If today were my last day, what would I prioritize? What would I let go of?",
	"What simple pleasures am I grateful for right now?",
	"What challenge in my life might be helping me grow, even if it doesn't feel like it?",
	"What changes in my life do I need to embrace instead of resist?",
];

export const casualPrompts = [
	"What's the best meal you've ever had?",
	"If you could have any superpower, what would it be and why?",
	"What's your favorite childhood memory?",
	"Describe your perfect weekend.",
	"If you could visit any fictional world, where would you go?",
	"What's your go-to comfort food?",
	"If you could have dinner with any celebrity, who would it be and what would you ask them?",
	"What's a hobby you've always wanted to pick up?",
	"What's the weirdest dream you've ever had?",
	"If your life were a movie, what genre would it be?",
	"What's your guilty pleasure TV show or movie?",
	"What's the funniest thing that's happened to you recently?",
	"If you could live anywhere in the world, where would it be?",
	"What's one skill you wish you had?",
	"What's the most adventurous thing you've ever done?",
	"If you had to eat one food for the rest of your life, what would it be?",
	"What's your favorite holiday tradition?",
	"Describe your dream vacation.",
	"What's your favorite way to relax after a long day?",
	"If you could instantly master one language, which one would it be?",
	"What's the most unusual place you've ever visited?",
	"If you won the lottery, what's the first thing you would do?",
	"What's your favorite song to sing in the shower?",
	"What's the best gift you've ever received?",
	"If you could time travel, would you go to the past or the future?",
	"What's your favorite board game or video game?",
	"What's one thing you're really good at?",
	"If you were an animal, what would you be and why?",
	"What's a fun fact most people don't know about you?",
	"If you could swap lives with anyone for a day, who would it be?",
	"What's your favorite ice cream flavor?",
	"If you could make a cameo in any movie, which one would it be?",
	"What's your favorite thing to do on a rainy day?",
	"What's the last book you read and loved?",
	"What's the most random act of kindness you've witnessed?",
	"What's your favorite childhood toy?",
	"If you had a personal theme song, what would it be?",
	"What's your go-to karaoke song?",
	"What's the best prank you've ever pulled or seen?",
	"What's your favorite smell and why?",
	"If you could have any job for a day, what would it be?",
	"What's the most interesting thing you've learned recently?",
	"What's your favorite kind of dessert?",
	"If you could only wear one outfit for the rest of your life, what would it be?",
	"What's the most beautiful place you've ever seen?",
	"What's your favorite childhood TV show?",
	"If you could play any instrument, what would it be?",
	"What's a tradition or ritual that means a lot to you?",
	"If you could magically learn any skill overnight, what would it be?",
	"What's the last song you listened to on repeat?",
	"If you could write a book, what would it be about?",
	"What's your go-to pizza topping?",
	"What's your favorite thing about weekends?",
	"If you could have a mythical creature as a pet, what would it be?",
	"What's the best advice you've ever received?",
	"If you could star in a TV show, what kind of show would it be?",
	"What's your favorite outdoor activity?",
	"If you could invent something, what would it be?",
	"What's a movie or book that made you laugh out loud?",
	"What's your favorite breakfast food?",
	"If you could live in any era, which one would you choose?",
	"What's your favorite thing to do with friends?",
	"What's a food you hated as a kid but love now?",
	"If you could be any character from a book or movie, who would it be?",
	"What's your go-to order at a coffee shop?",
	"What's a memory that always makes you smile?",
	"What's your favorite way to spend a lazy Sunday?",
	"If you could only watch one movie for the rest of your life, what would it be?",
	"What's the quirkiest habit you have?",
	"What's your favorite holiday and why?",
	"What's a goal you've been working toward recently?",
	"What's your favorite snack?",
	"If you could design your dream house, what would it look like?",
	"What's your favorite type of weather?",
	"What's your favorite childhood game?",
	"What's a skill you learned as a child that you still use today?",
	"If you could try any extreme sport, what would it be?",
	"What's your favorite way to celebrate your birthday?",
	"What's a fashion trend you secretly love?",
	"What's your favorite thing about your favorite season?",
	"If you could meet any historical figure, who would it be?",
	"What's your favorite type of cake?",
	"What's the last thing you learned to cook or bake?",
	"If you could create your own holiday, what would it be about?",
	"What's your favorite way to spend a day off?",
	"If you could instantly teleport anywhere, where would you go?",
	"What's your favorite type of sandwich?",
	"What's a skill or hobby you admire in others?",
	"What's your favorite kind of party?",
	"If you could learn one magic spell, what would it do?",
	"What's your favorite thing about your favorite animal?",
	"What's the best compliment you've ever received?",
	"If you could redo one day in your life, which one would it be?",
	"What's your favorite thing to do when you're feeling creative?",
	"If you could only listen to one band or artist forever, who would it be?",
	"What's your favorite kind of soup?",
	"If you could live in any kind of home, what would it be like?",
	"What's your favorite icebreaker question?",
	"What's your favorite way to stay active?",
	"What's your dream car or mode of transportation?",
	"If you could change one thing about your daily routine, what would it be?",
	"What's your favorite smell from childhood?",
	"What's the last thing that made you laugh out loud?",
	"What's your favorite thing to do on a sunny day?",
	"If you could try any career for a week, what would it be?",
	"What's your favorite dessert to share with others?",
	"If you could create a new emoji, what would it be?",
	"What's your favorite kind of pie?",
	"What's the most exciting thing you're looking forward to?",
	"What's your favorite memory from a vacation?",
	"If you could adopt any unusual pet, what would it be?",
	"What's your favorite thing to do when you're bored?",
	"If you could design a theme park, what would the theme be?",
	"What's your favorite thing to eat at a barbecue?",
	"If you could make your own pizza flavor, what would it be?",
	"What's your favorite thing about where you live?",
	"What's your favorite type of flower or plant?",
	"What's the most fun you've ever had with your friends?",
	"If you could decorate your home any way you wanted, what would it look like?",
	"What's the best meal you've ever cooked for someone else?",
	"If you could spend a day with your favorite fictional character, what would you do?",
	"What's your favorite memory from a holiday celebration?",
	"If you could invent a gadget to make life easier, what would it do?",
];
